version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.3.9-cli-stretch

    working_directory: ~/repo

    steps:
      - run:
          name: Install bcmath and gmp extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y libgmp-dev libxml2-dev libpng-dev
            sudo rm -rf /var/lib/apt/lists/*
            sudo docker-php-ext-configure bcmath
            sudo docker-php-ext-configure gmp
            sudo docker-php-ext-configure soap
            sudo docker-php-ext-install bcmath gmp soap
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - tl-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - tl-dependencies-

      - run:
          name: Install dependencies
          command: |
            cd ~/repo
            composer install -n --prefer-dist --no-scripts
      - save_cache:
          paths:
            - ~/repo/app/vendor
          key: tl-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run:
          name: Run tests
          command: |
            cd ~/repo
            cp .env.testing .env
            ./vendor/bin/phpunit
  deploy:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: "expence"
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
